version: "1.2"
services:
  travel-core:
    build: "."
    ports:
      - "3000:3000"
    networks:
      - appnet
  booking-engine:
    build: "."
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
