// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: booking.proto

package ticket_engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeatConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatCount     int32                  `protobuf:"varint,1,opt,name=seatCount,proto3" json:"seatCount,omitempty"`
	Berth         string                 `protobuf:"bytes,2,opt,name=berth,proto3" json:"berth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatConfig) Reset() {
	*x = SeatConfig{}
	mi := &file_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatConfig) ProtoMessage() {}

func (x *SeatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatConfig.ProtoReflect.Descriptor instead.
func (*SeatConfig) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{0}
}

func (x *SeatConfig) GetSeatCount() int32 {
	if x != nil {
		return x.SeatCount
	}
	return 0
}

func (x *SeatConfig) GetBerth() string {
	if x != nil {
		return x.Berth
	}
	return ""
}

type Passenger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Berth         string                 `protobuf:"bytes,2,opt,name=berth,proto3" json:"berth,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Passenger) Reset() {
	*x = Passenger{}
	mi := &file_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passenger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passenger) ProtoMessage() {}

func (x *Passenger) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passenger.ProtoReflect.Descriptor instead.
func (*Passenger) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{1}
}

func (x *Passenger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Passenger) GetBerth() string {
	if x != nil {
		return x.Berth
	}
	return ""
}

func (x *Passenger) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type BookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrainId       string                 `protobuf:"bytes,1,opt,name=trainId,proto3" json:"trainId,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Class         string                 `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	Quota         string                 `protobuf:"bytes,5,opt,name=quota,proto3" json:"quota,omitempty"`
	Passengers    []*Passenger           `protobuf:"bytes,6,rep,name=passengers,proto3" json:"passengers,omitempty"`
	SeatConfig    []*SeatConfig          `protobuf:"bytes,7,rep,name=seatConfig,proto3" json:"seatConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRequest) Reset() {
	*x = BookingRequest{}
	mi := &file_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRequest) ProtoMessage() {}

func (x *BookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRequest.ProtoReflect.Descriptor instead.
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{2}
}

func (x *BookingRequest) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *BookingRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *BookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookingRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *BookingRequest) GetQuota() string {
	if x != nil {
		return x.Quota
	}
	return ""
}

func (x *BookingRequest) GetPassengers() []*Passenger {
	if x != nil {
		return x.Passengers
	}
	return nil
}

func (x *BookingRequest) GetSeatConfig() []*SeatConfig {
	if x != nil {
		return x.SeatConfig
	}
	return nil
}

type Seats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatNo        string                 `protobuf:"bytes,1,opt,name=seatNo,proto3" json:"seatNo,omitempty"`
	Berth         string                 `protobuf:"bytes,2,opt,name=berth,proto3" json:"berth,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Info          *Passenger             `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seats) Reset() {
	*x = Seats{}
	mi := &file_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seats) ProtoMessage() {}

func (x *Seats) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seats.ProtoReflect.Descriptor instead.
func (*Seats) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{3}
}

func (x *Seats) GetSeatNo() string {
	if x != nil {
		return x.SeatNo
	}
	return ""
}

func (x *Seats) GetBerth() string {
	if x != nil {
		return x.Berth
	}
	return ""
}

func (x *Seats) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Seats) GetInfo() *Passenger {
	if x != nil {
		return x.Info
	}
	return nil
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pnr           string                 `protobuf:"bytes,1,opt,name=pnr,proto3" json:"pnr,omitempty"`
	Seat          []*Seats               `protobuf:"bytes,2,rep,name=seat,proto3" json:"seat,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{4}
}

func (x *BookingResponse) GetPnr() string {
	if x != nil {
		return x.Pnr
	}
	return ""
}

func (x *BookingResponse) GetSeat() []*Seats {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *BookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_booking_proto protoreflect.FileDescriptor

const file_booking_proto_rawDesc = "" +
	"\n" +
	"\rbooking.proto\x12\x0eticket_backend\"@\n" +
	"\n" +
	"SeatConfig\x12\x1c\n" +
	"\tseatCount\x18\x01 \x01(\x05R\tseatCount\x12\x14\n" +
	"\x05berth\x18\x02 \x01(\tR\x05berth\"G\n" +
	"\tPassenger\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05berth\x18\x02 \x01(\tR\x05berth\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"\xf9\x01\n" +
	"\x0eBookingRequest\x12\x18\n" +
	"\atrainId\x18\x01 \x01(\tR\atrainId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x12\x14\n" +
	"\x05quota\x18\x05 \x01(\tR\x05quota\x129\n" +
	"\n" +
	"passengers\x18\x06 \x03(\v2\x19.ticket_backend.PassengerR\n" +
	"passengers\x12:\n" +
	"\n" +
	"seatConfig\x18\a \x03(\v2\x1a.ticket_backend.SeatConfigR\n" +
	"seatConfig\"|\n" +
	"\x05Seats\x12\x16\n" +
	"\x06seatNo\x18\x01 \x01(\tR\x06seatNo\x12\x14\n" +
	"\x05berth\x18\x02 \x01(\tR\x05berth\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12-\n" +
	"\x04info\x18\x04 \x01(\v2\x19.ticket_backend.PassengerR\x04info\"\x82\x01\n" +
	"\x0fBookingResponse\x12\x10\n" +
	"\x03pnr\x18\x01 \x01(\tR\x03pnr\x12)\n" +
	"\x04seat\x18\x02 \x03(\v2\x15.ticket_backend.SeatsR\x04seat\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2^\n" +
	"\rBookingEngine\x12M\n" +
	"\n" +
	"BookTicket\x12\x1e.ticket_backend.BookingRequest\x1a\x1f.ticket_backend.BookingResponseB$Z\"booking-engine/proto;ticket_engineb\x06proto3"

var (
	file_booking_proto_rawDescOnce sync.Once
	file_booking_proto_rawDescData []byte
)

func file_booking_proto_rawDescGZIP() []byte {
	file_booking_proto_rawDescOnce.Do(func() {
		file_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_proto_rawDesc), len(file_booking_proto_rawDesc)))
	})
	return file_booking_proto_rawDescData
}

var file_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_booking_proto_goTypes = []any{
	(*SeatConfig)(nil),      // 0: ticket_backend.SeatConfig
	(*Passenger)(nil),       // 1: ticket_backend.Passenger
	(*BookingRequest)(nil),  // 2: ticket_backend.BookingRequest
	(*Seats)(nil),           // 3: ticket_backend.Seats
	(*BookingResponse)(nil), // 4: ticket_backend.BookingResponse
}
var file_booking_proto_depIdxs = []int32{
	1, // 0: ticket_backend.BookingRequest.passengers:type_name -> ticket_backend.Passenger
	0, // 1: ticket_backend.BookingRequest.seatConfig:type_name -> ticket_backend.SeatConfig
	1, // 2: ticket_backend.Seats.info:type_name -> ticket_backend.Passenger
	3, // 3: ticket_backend.BookingResponse.seat:type_name -> ticket_backend.Seats
	2, // 4: ticket_backend.BookingEngine.BookTicket:input_type -> ticket_backend.BookingRequest
	4, // 5: ticket_backend.BookingEngine.BookTicket:output_type -> ticket_backend.BookingResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_booking_proto_init() }
func file_booking_proto_init() {
	if File_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_proto_rawDesc), len(file_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_proto_goTypes,
		DependencyIndexes: file_booking_proto_depIdxs,
		MessageInfos:      file_booking_proto_msgTypes,
	}.Build()
	File_booking_proto = out.File
	file_booking_proto_goTypes = nil
	file_booking_proto_depIdxs = nil
}
