// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/booking.proto

package ticket_engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookingEngine_BookTicket_FullMethodName = "/ticket_backend.BookingEngine/BookTicket"
)

// BookingEngineClient is the client API for BookingEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingEngineClient interface {
	BookTicket(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error)
}

type bookingEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingEngineClient(cc grpc.ClientConnInterface) BookingEngineClient {
	return &bookingEngineClient{cc}
}

func (c *bookingEngineClient) BookTicket(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, BookingEngine_BookTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingEngineServer is the server API for BookingEngine service.
// All implementations must embed UnimplementedBookingEngineServer
// for forward compatibility.
type BookingEngineServer interface {
	BookTicket(context.Context, *BookingRequest) (*BookingResponse, error)
	mustEmbedUnimplementedBookingEngineServer()
}

// UnimplementedBookingEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingEngineServer struct{}

func (UnimplementedBookingEngineServer) BookTicket(context.Context, *BookingRequest) (*BookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookTicket not implemented")
}
func (UnimplementedBookingEngineServer) mustEmbedUnimplementedBookingEngineServer() {}
func (UnimplementedBookingEngineServer) testEmbeddedByValue()                       {}

// UnsafeBookingEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingEngineServer will
// result in compilation errors.
type UnsafeBookingEngineServer interface {
	mustEmbedUnimplementedBookingEngineServer()
}

func RegisterBookingEngineServer(s grpc.ServiceRegistrar, srv BookingEngineServer) {
	// If the following call pancis, it indicates UnimplementedBookingEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookingEngine_ServiceDesc, srv)
}

func _BookingEngine_BookTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingEngineServer).BookTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingEngine_BookTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingEngineServer).BookTicket(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingEngine_ServiceDesc is the grpc.ServiceDesc for BookingEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticket_backend.BookingEngine",
	HandlerType: (*BookingEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookTicket",
			Handler:    _BookingEngine_BookTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/booking.proto",
}
